SellingMovieTickets/Controllers/CustomerManagementController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SellingMovieTickets.Models.Entities;
using SellingMovieTickets.Models.Enum;
using SellingMovieTickets.Models.ViewModels.AccountManagement;
using SellingMovieTickets.Repository;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using System.Data;
using System.Security.Claims;

namespace SellingMovieTickets.Controllers
{
    public class CustomerManagementController : Controller
    {
        private DataContext _dataContext;
        private SignInManager<AppUserModel> _signInManager;

        public CustomerManagementController(DataContext dataContext, SignInManager<AppUserModel> signInManager)
        {
            _dataContext = dataContext;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            var idCustomer = User.FindFirstValue(ClaimUserLogin.Id);
            var user = await _dataContext.Users.Where(x => x.Id == idCustomer).FirstOrDefaultAsync();
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> EditProfile(AppUserModel model)
        {
            if (model != null)
            {
                var user = await _dataContext.Users.Where(x => x.Id == model.Id).FirstOrDefaultAsync();
                user.LastName = model.LastName;
                user.FirstName = model.FirstName;
                user.FullName = model.LastName + " " + model.FirstName;
                user.Address = model.Address;
                user.PhoneNumber = model.PhoneNumber;
                _dataContext.Users.Update(user);
                await _dataContext.SaveChangesAsync();

                var claims = new List<Claim>
                                {
                                    new Claim(ClaimUserLogin.Id, user.Id),
                                    new Claim(ClaimUserLogin.Avatar, user.Avatar),
                                    new Claim(ClaimUserLogin.FullName, user.FullName),
                                    new Claim(ClaimUserLogin.Email, user.Email),
                                    new Claim(ClaimUserLogin.Role, User.FindFirstValue(ClaimUserLogin.Role))
                                };
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = true, // Cookie tồn tại sau khi đóng trình duyệt
                    ExpiresUtc = DateTimeOffset.UtcNow.AddHours(1)
                };
                await _signInManager.SignInWithClaimsAsync(user, authProperties, claims);

                TempData["Success"] = "Cập nhật thông tin thành công.";
                return RedirectToAction("Index", "Home");
            }

            TempData["Error"] = "Cập nhật thông tin thất bại.";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetInfoHistoryTicket()
        {
            var idCustomer = User.FindFirstValue(ClaimUserLogin.Id);

            var tickets = await _dataContext.Orders
                .Where(o => o.CustomerManagement.UserId == idCustomer && o.StatusOrder == "00")
                .Include(o => o.OrderDetails)
                .Include(o => o.CinemaShowTime.Movie)
                .ToListAsync();

            var historyTickets = tickets.Select(order => new HistoryTicket
            {
                TradingDate = order.CreateDate,
                NameMovie = order.CinemaShowTime.Movie.Name,
                NumberOfTickets = order.OrderDetails.Count,
                TotalAmount = order.OrderDetails.Sum(detail => detail.Price)
            }).ToList();

            return Json(historyTickets);
        }

        [HttpGet]
        public async Task<IActionResult> GetInfoHistoryPoint()
        {
            var idCustomer = User.FindFirstValue(ClaimUserLogin.Id);
            var historyPoints = await _dataContext.CustomerPointsHistories
                   .Include(x => x.Customer)
                   .Include(x => x.Order)
                   .Where(x => x.Customer.UserId == idCustomer)
                   .Select(x => new
                   {
                       x.Id,
                       x.PointsChanged,
                       x.TransactionDate,
                       x.PointChangeStatus,
                       x.Order.OrderCode,
                   })
                   .ToListAsync();
            return Json(historyPoints);
        }
    }
}

SellingMovieTickets/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SellingMovieTickets.Areas.Admin.Models.ViewModels.Movie;
using SellingMovieTickets.Models.Enum;
using SellingMovieTickets.Repository;

namespace SellingMovieTickets.Controllers
{
    public class MenuController : Controller
    {
        private readonly DataContext _context;

        public MenuController(DataContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult MenuTop()
        {
            var items = _context.Categories
                .Where(x => x.Status == Status.Show)
                .Select(x => new { x.Name, x.Slug })   
                .ToList();
            return Json(items);
        }

        public IActionResult MenuSlider()
        {
            var items = _context.Advs.Where(x => x.Status == Status.Show).ToList();
            return PartialView("_SliderPartial", items);
        }

       


    }
}

SellingMovieTickets/Views/Shared/_Layout.cshtml
@using SellingMovieTickets.Models.Enum
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Rạp chiếu phim Umi</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Umi Shop">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="~/assets/styles/bootstrap4/bootstrap.min.css">
    <link href="~/assets/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="icon" href="~/media/image/logo.gif" type="image/x-icon">

    <link rel="stylesheet" type="text/css" href="~/assets/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/assets/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="~/assets/plugins/OwlCarousel2-2.2.1/animate.css">

    <link rel="stylesheet" type="text/css" href="~/assets/styles/main_styles.css">
    <link rel="stylesheet" type="text/css" href="~/assets/styles/responsive.css">
    <link href="~/css/main.css" rel="stylesheet" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.12.4/dist/sweetalert2.min.css" rel="stylesheet">
    <link href="~/assetsaccount/css/register_login.css" rel="stylesheet" />

    <!-- Thêm Bootstrap CSS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

    @* Font Awesome *@
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
</head>

<body>
    <div class="super_container">
        <header class="header">
            <nav class="nav_menu navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="#">
                    <img src="~/media/image/Logo.gif" alt="NCC Logo" class="logo">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse menu_top" id="navbarNav">
                    <ul class="navbar-nav mr-auto" id="menuList"></ul>
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            @if (User.Identity?.IsAuthenticated ?? false)
                            {
                                var fullName = User.FindFirst(ClaimUserLogin.FullName)?.Value;
                                <div class="box_inforUser">
                                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <img src="~/media/image/avatar.jpg" class="avatar rounded-circle" alt="User Avatar">
                                        <span>@fullName</span>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                                        <a asp-controller="CustomerManagement" asp-action="Index" class="dropdown-item"><i class="fa fa-user mr_12" aria-hidden="true"></i>Thông tin cá nhân</a>
                                        <a asp-controller="Account" asp-action="Logout" class="dropdown-item"><i class="fa fa-lock mr_12" aria-hidden="true"></i>Đăng xuất</a>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="box_account">
                                    <a asp-controller="Account" asp-action="Register">
                                        <button type="button" class="btn btn-register mr_22">Đăng ký</button>
                                    </a>
                                    <a asp-controller="Account" asp-action="Login">
                                        <button type="button" class="btn btn-login">Đăng nhập</button>
                                    </a>
                                </div>
                            }
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <partial name="_Notification" />
        <main>
            <div id="main-content" style="margin-top: 90px;">
                @RenderBody()
            </div>
        </main>

        <!-- Footer -->
        <footer class="bg-dark text-white py-4">
            <div class="container">
                <div class="row text-center">
                    <div class="col-12 mb-3">
                        <a href="#" class="text-white mx-2">Chính sách</a>
                        <a href="#" class="text-white mx-2">Lịch chiếu</a>
                        <a href="#" class="text-white mx-2">Tin tức</a>
                        <a href="#" class="text-white mx-2">Giá vé</a>
                        <a href="#" class="text-white mx-2">Hỏi đáp</a>
                        <a href="#" class="text-white mx-2">Liên hệ</a>
                    </div>

                    <div class="col-12 mb-3">
                        <a href="#"><img src="~/media/image/facebook.png" alt="Facebook" class="mx-1 icon"></a>
                        <a href="#"><img src="~/media/image/zalo.png" alt="Zalo" class="mx-1 icon"></a>
                        <a href="#"><img src="~/media/image/youtube.png" alt="YouTube" class="mx-1 icon"></a>
                        <a href="#"><img src="~/media/image/google_play.png" alt="Google Play" class="mx-2 icon"></a>
                        <a href="#"><img src="~/media/image/apple_store.png" alt="App Store" class="mx-2 icon"></a>
                    </div>
                    <div class="col-12 mb-2">
                        <p>
                            Cơ quan chủ quản: BỘ VĂN HÓA, THỂ THAO VÀ DU LỊCH<br>
                            Bản quyền thuộc Công ty Umi.<br>
                            Địa chỉ: 87 Láng Hạ, Quận Ba Đình, Tp. Hà Nội - Điện thoại: 024.35141793
                        </p>
                    </div>

                    <div class="col-12">
                        <p>Copyright 2024. NCC All Rights Reserved. Dev by NgocTan.vn</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/assets/js/jquery-3.2.1.min.js"></script>
    <script src="~/assets/styles/bootstrap4/popper.js"></script>
    <script src="~/assets/styles/bootstrap4/bootstrap.min.js"></script>
    <script src="~/assets/plugins/easing/easing.js"></script>
    <script src="~/assets/plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
    <script src="~/assets/js/custom.js"></script>

    <script src="~/assets/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            var isLoggedIn = @User.Identity.IsAuthenticated.ToString().ToLower();

            $.ajax({
                url: '@Url.Action("MenuTop", "Menu")',
                type: 'GET',
                success: function (data) {
                    if (data && data.length) {
                        var menuHtml = '';
                        data.forEach(function (item) {
                            const loginUrl = '@Url.Action("Login", "Account")';
                            if (item.slug === "lich-chieu" && !isLoggedIn) {
                                menuHtml += `<li class="nav-item active">
                                                                                                    <a href="${loginUrl}" class="nav-link nav_item">${item.name}</a>
                                                                                             </li>`;
                            } else {
                                menuHtml += `<li class="nav-item active">
                                                                                                     <a href="/${item.slug}" class="nav-link nav_item">${item.name}</a>
                                                                                                 </li>`;
                            }
                        });
                        $('#menuList').html(menuHtml);
                    }
                },
                error: function (error) {
                    console.log("Error loading menu items:", error);
                }
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SellingMovieTickets/Views/Shared/_MovieCommingSoonPartial.cshtml
@using SellingMovieTickets.Areas.Admin.Models.ViewModels.Movie
@model IEnumerable<MovieViewModel>

@if (Model != null && Model.Any())
{
    @foreach (var item in Model)
    {
        <div class="col-md-3 col-6 movie-item">
            <img src="@item.Image" alt="Movie Image">
            <div class="movie-info">
                <div class="box_account ">
                    <p>@item.Genres</p>
                    <p>@item.ReleaseDate.ToString("dd/MM/yyyy")</p>
                </div>
                <h6>@item.Name</h6>
            </div>
        </div>
    }
}

SellingMovieTickets/Views/Shared/_MovieNowShowingPartial.cshtml
@using SellingMovieTickets.Areas.Admin.Models.ViewModels.Movie
@model IEnumerable<MovieViewModel>

@if (Model != null && Model.Any())
{
    @foreach (var item in Model)
    {
        <div class="col-md-3 col-6 movie-item">
            <img src="@item.Image" alt="Movie Image">
            <div class="movie-info">
                <div class="box_account ">
                    <p>@item.Genres</p>
                    <p>@item.ReleaseDate.ToString("dd/MM/yyyy")</p>
                </div>
                <h6>@item.Name</h6>
            </div>
        </div>
    }
}

SellingMovieTickets/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.success('@TempData["Success"]');
    </script>
}

@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.error('@TempData["Error"]')
    </script>
}

SellingMovieTickets/Views/Shared/_SliderPartial.cshtml
@using SellingMovieTickets.Models.Entities
@model IEnumerable<AdvModel>

<style>
    .carousel-item img {
        width: 100vw;
        height: auto;
        max-height: 100vh;
        object-fit: cover;
    }

    .carousel-control-prev,
    .carousel-control-next {
        width: 34px;
        height: 34px;
        margin: 20px;
        background-color: rgba(0, 0, 0, 0.5);
        border-radius: 50%;
        top: 50%;
    }

    .carousel-control-prev-icon,
    .carousel-control-next-icon {
        background-size: 50%;
        filter: invert(1);
    }

</style>

@if (Model != null && Model.Any())
{
    <div id="sliderCarousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3000">
        <div class="carousel-inner">
            <div class="carousel-indicators">
                @for (int i = 0; i < Model.Count(); i++)
                {
                    <button type="button" data-bs-target="#sliderCarousel" data-bs-slide-to="@i" class="@(i == 0 ? "active" : "")" aria-current="@(i == 0 ? "true" : "false")"></button>
                }
            </div>

            <div class="carousel-inner">
                @foreach (var item in Model)
                {
                    <div class="carousel-item @(Model.First() == item ? "active" : "")">
                        <img src="@item.Image" class="d-block w-100" alt="@item.Title" style="width: 100vw; height: auto; max-height: 100vh; object-fit: cover;">
                    </div>
                }
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#sliderCarousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#sliderCarousel" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </button>
        </div>
    </div>
}