SellingMovieTickets/Controllers/CustomerManagementController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SellingMovieTickets.Models.Entities;
using SellingMovieTickets.Models.Enum;
using SellingMovieTickets.Models.ViewModels.AccountManagement;
using SellingMovieTickets.Repository;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using System.Data;
using System.Security.Claims;

namespace SellingMovieTickets.Controllers
{
    public class CustomerManagementController : Controller
    {
        private DataContext _dataContext;
        private SignInManager<AppUserModel> _signInManager;

        public CustomerManagementController(DataContext dataContext, SignInManager<AppUserModel> signInManager)
        {
            _dataContext = dataContext;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            var idCustomer = User.FindFirstValue(ClaimUserLogin.Id);
            var user = await _dataContext.Users.Where(x => x.Id == idCustomer).FirstOrDefaultAsync();
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> EditProfile(AppUserModel model)
        {
            if (model != null)
            {
                var user = await _dataContext.Users.Where(x => x.Id == model.Id).FirstOrDefaultAsync();
                user.LastName = model.LastName;
                user.FirstName = model.FirstName;
                user.FullName = model.LastName + " " + model.FirstName;
                user.Address = model.Address;
                user.PhoneNumber = model.PhoneNumber;
                _dataContext.Users.Update(user);
                await _dataContext.SaveChangesAsync();

                var claims = new List<Claim>
                                {
                                    new Claim(ClaimUserLogin.Id, user.Id),
                                    new Claim(ClaimUserLogin.Avatar, user.Avatar),
                                    new Claim(ClaimUserLogin.FullName, user.FullName),
                                    new Claim(ClaimUserLogin.Email, user.Email),
                                    new Claim(ClaimUserLogin.Role, User.FindFirstValue(ClaimUserLogin.Role))
                                };
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = true, // Cookie tồn tại sau khi đóng trình duyệt
                    ExpiresUtc = DateTimeOffset.UtcNow.AddHours(1)
                };
                await _signInManager.SignInWithClaimsAsync(user, authProperties, claims);

                TempData["Success"] = "Cập nhật thông tin thành công.";
                return RedirectToAction("Index", "Home");
            }

            TempData["Error"] = "Cập nhật thông tin thất bại.";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetInfoHistoryTicket()
        {
            var idCustomer = User.FindFirstValue(ClaimUserLogin.Id);

            var tickets = await _dataContext.Orders
                .Where(o => o.CustomerManagement.UserId == idCustomer && o.StatusOrder == "00")
                .Include(o => o.OrderDetails)
                .Include(o => o.CinemaShowTime.Movie)
                .ToListAsync();

            var historyTickets = tickets.Select(order => new HistoryTicket
            {
                TradingDate = order.CreateDate,
                NameMovie = order.CinemaShowTime.Movie.Name,
                NumberOfTickets = order.OrderDetails.Count,
                TotalAmount = order.OrderDetails.Sum(detail => detail.Price)
            }).ToList();

            return Json(historyTickets);
        }

        [HttpGet]
        public async Task<IActionResult> GetInfoHistoryPoint()
        {
            var idCustomer = User.FindFirstValue(ClaimUserLogin.Id);
            var historyPoints = await _dataContext.CustomerPointsHistories
                   .Include(x => x.Customer)
                   .Include(x => x.Order)
                   .Where(x => x.Customer.UserId == idCustomer)
                   .Select(x => new
                   {
                       x.Id,
                       x.PointsChanged,
                       x.TransactionDate,
                       x.PointChangeStatus,
                       x.Order.OrderCode,
                   })
                   .ToListAsync();
            return Json(historyPoints);
        }
    }
}

SellingMovieTickets/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SellingMovieTickets.Areas.Admin.Models.ViewModels.Movie;
using SellingMovieTickets.Models.Enum;
using SellingMovieTickets.Repository;

namespace SellingMovieTickets.Controllers
{
    public class MovieController : Controller
    {
        private readonly DataContext _context;

        public MovieController(DataContext context)
        {
            _context = context;
        }

        public IActionResult MovieNowShowing()
        {
            var moviesQuery = _context.Movies.Include(m => m.MovieCategoryMappings)
            .ThenInclude(mcm => mcm.MovieCategory)
            .Where(x => x.Status == Status.Show && x.IsOutstanding && x.StatusMovie == StatusMovie.NowShowing) 
            .OrderByDescending(x => x.Id)
            .Take(8)  
            .AsQueryable();

            var movieViewModel = moviesQuery.Select(x => new MovieViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                ReleaseDate = x.ReleaseDate,
                Duration = x.Duration,
                MovieLanguageFormat = x.MovieLanguageFormat,
                MovieFormat = x.MovieFormat,
                StatusMovie = x.StatusMovie,
                Origin = x.Origin,
                Price = x.Price,
                Director = x.Director,
                Actor = x.Actor,
                Rating = x.Rating,
                TrailerUrl = x.TrailerUrl,
                Status = x.Status,
                Image = x.Image,
                CreateBy = x.CreateBy,
                CreateDate = x.CreateDate,
                ModifiedBy = x.ModifiedBy,
                ModifiedDate = x.ModifiedDate,
                Genres = string.Join(", ", x.MovieCategoryMappings.Select(mcm => mcm.MovieCategory.CategoryName))
            }).ToList();

            return PartialView("_MovieNowShowingPartial", movieViewModel);
        }

        public IActionResult MovieCommingSoon()
        {
            var moviesQuery = _context.Movies.Include(m => m.MovieCategoryMappings)
            .ThenInclude(mcm => mcm.MovieCategory)
            .Where(x => x.Status == Status.Show && x.IsOutstanding && x.StatusMovie == StatusMovie.CommingSoon)
            .OrderByDescending(x => x.Id)
            .Take(8)
            .AsQueryable();

            var movieViewModel = moviesQuery.Select(x => new MovieViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                ReleaseDate = x.ReleaseDate,
                Duration = x.Duration,
                MovieLanguageFormat = x.MovieLanguageFormat,
                MovieFormat = x.MovieFormat,
                StatusMovie = x.StatusMovie,
                Origin = x.Origin,
                Price = x.Price,
                Director = x.Director,
                Actor = x.Actor,
                Rating = x.Rating,
                TrailerUrl = x.TrailerUrl,
                Status = x.Status,
                Image = x.Image,
                CreateBy = x.CreateBy,
                CreateDate = x.CreateDate,
                ModifiedBy = x.ModifiedBy,
                ModifiedDate = x.ModifiedDate,
                Genres = string.Join(", ", x.MovieCategoryMappings.Select(mcm => mcm.MovieCategory.CategoryName))
            }).ToList();

            return PartialView("_MovieCommingSoonPartial", movieViewModel);
        }



    }
}

SellingMovieTickets/Controllers/OtherServicesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SellingMovieTickets.Areas.Admin.Models.ViewModels.OtherServices;
using SellingMovieTickets.Repository;

namespace SellingMovieTickets.Controllers
{
    public class OtherServicesController : Controller
    {

        private readonly DataContext _dataContext;

        public OtherServicesController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetListOtherServices()
        {
            var list = await _dataContext.OtherServices
                 .Select(service => new OtherServicesViewModel
                 {
                     Id = service.Id,
                     Name = service.Name,
                     Price = service.Price,
                     Description = service.Description,
                     Image = service.Image,
                     Status = service.Status,
                     CreateBy = service.CreateBy,
                     CreateDate = service.CreateDate,
                     ModifiedBy = service.ModifiedBy,
                     ModifiedDate = service.ModifiedDate
                 })
                 .ToListAsync();
            return Json(list);
        }


    }
}

SellingMovieTickets/Areas/Admin/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        toastr.success('@TempData["Success"]');
    </script>
}

SellingMovieTickets/Areas/Admin/Views/Shared/_Paging.cshtml
@using SellingMovieTickets.Models.Enum
@model Paginate;

<div class="container">
    @if (Model.TotalPages > 0) 
    {
        <ul class="pagination justify-content-end">

            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="Index"
                       asp-route-pg="1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="Index"
                       asp-route-pg="@(Model.CurrentPage - 1)">Previous</a>
                </li>
            }
            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++) //1 = 1 <= 2
            {
                <li class="page-item @(pge==Model.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>
            }
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="Index"
                       asp-route-pg="@(Model.CurrentPage+1)">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="Index"
                       asp-route-pg="@(Model.TotalPages)">Last</a>
                </li>
            }
        </ul>
    }
</div>

SellingMovieTickets/Areas/Admin/Views/Shared/_PartialSidebar.cshtml
@using SellingMovieTickets.Models.Enum

<div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            @if (User.Identity?.IsAuthenticated ?? false)
            {
                var avatar = User.FindFirst("Avatar")?.Value != null
                ? $"{User.FindFirst("Avatar")?.Value}" : "";
                <img src="@avatar" class="img-circle elevation-2" alt="User Image">
            }
        </div>
        <div class="info">
            @if (User.Identity?.IsAuthenticated ?? false)
            {
                var fullName = User.FindFirst(ClaimUserLogin.FullName)?.Value;
                <a href="#"><i aria-hidden="true"></i>@fullName</a>
            }
        </div>
    </div>

    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
                <a asp-controller="Category" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-list"></i>
                    <p>Danh mục</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="News" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-newspaper"></i>
                    <p>Tin tức</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Adv" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-ad"></i>
                    <p>Quảng cáo</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Promotion" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-tag"></i>
                    <p>Khuyến mãi</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-box"></i>
                    <p>
                        Quản lý phim
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a asp-controller="MovieCategory" asp-action="Index" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Thể loại phim</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Movie" asp-action="Index" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Phim</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a asp-controller="CinemaShowTime" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-film"></i>
                    <p>Suất chiếu</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Room" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-tag"></i>
                    <p>Phòng chiếu</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="OtherServices" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-utensils"></i>
                    <p>Đồ ăn/ đồ uống</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Order" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-receipt"></i>
                    <p>Hóa đơn</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Ticket" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-ticket-alt"></i>
                    <p>Vé xem phim</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="CustomerManagement" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-star"></i>
                    <p>Điểm thưởng khách hàng</p>
                </a>
            </li>
            @if (User.Identity?.IsAuthenticated ?? false)
            {
                var role = User.FindFirst(ClaimUserLogin.Role)?.Value;
                @if (role == Role.Admin)
                {
                    <li class="nav-item">
                        <a asp-controller="Role" asp-action="Index" class="nav-link">
                            <i class="nav-icon fas fa-user-tag"></i>
                            <p>Vai trò</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Account" asp-action="Index" class="nav-link">
                            <i class="nav-icon fas fa-users"></i>
                            <p>Tài khoản</p>
                        </a>
                    </li>
                }
            }
        </ul>
    </nav>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var navLinks = document.querySelectorAll('.nav-link');
        var currentUrl = window.location.href;

        navLinks.forEach(function (link) {
            if (link.href === currentUrl) {
                link.classList.add('active');
            }
        });
    });
</script>